# Generated by Django 4.1.3 on 2022-11-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrockersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokers', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClearerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DerivativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivative', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spread', models.CharField(max_length=100, null=True)),
                ('Outright', models.CharField(max_length=100, null=True)),
                ('Swaps_swaps', models.CharField(max_length=100, null=True)),
                ('crack', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClearerRatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=100, null=True)),
                ('clearer_cost', models.IntegerField(null=True)),
                ('exchange_cost', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('clearer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.clearermodel')),
                ('derivative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.derivativemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applymode', models.CharField(choices=[('start ', 'start'), ('only for', 'only for')], default='select', max_length=100)),
                ('brokerage', models.IntegerField(null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.derivativemodel')),
                ('select_brocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo_app.brockersmodel')),
            ],
        ),
    ]
