# Generated by Django 4.1.3 on 2022-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0002_brockersmodel_clearermodel_derivativemodel_typemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalblotter',
            name='Trade_reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
